apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: storguard-prometheus
    url: http://storguard-prometheus:9090
    isDefault: true
    access: proxy
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
